//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancialSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class expense_and_income
    {
        public int expense_income_id { get; set; }
        public string amount { get; set; }
        public string reason { get; set; }
        public System.DateTime date { get; set; }
        public int payee_or_payer_id { get; set; }
        public string expense_or_income { get; set; }
    
        public virtual payee_and_payer payee_and_payer { get; set; }
    }
}
